// Mocks generated by Mockito 5.4.4 from annotations
// in Woloo_Smart_hygiene/test/dashbaord_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i8;

import 'package:flutter/widgets.dart' as _i9;
import 'package:get/utils.dart' as _i3;
import 'package:get_storage/get_storage.dart' as _i2;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:Woloo_Smart_hygiene/core/local/global_storage.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMicrotask_0 extends _i1.SmartFake implements _i2.Microtask {
  _FakeMicrotask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetQueue_1 extends _i1.SmartFake implements _i3.GetQueue {
  _FakeGetQueue_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueStorage_2<T> extends _i1.SmartFake
    implements _i2.ValueStorage<T> {
  _FakeValueStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_4 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GlobalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGlobalStorage extends _i1.Mock implements _i5.GlobalStorage {
  MockGlobalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void saveToken({required String? accessToken}) => super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [],
          {#accessToken: accessToken},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getToken,
            [],
          ),
        ),
      ) as String);

  @override
  void removeToken() => super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveProfile({required String? profileName}) => super.noSuchMethod(
        Invocation.method(
          #saveProfile,
          [],
          {#profileName: profileName},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getProfileName() => (super.noSuchMethod(
        Invocation.method(
          #getProfileName,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getProfileName,
            [],
          ),
        ),
      ) as String);

  @override
  void removeProfile() => super.noSuchMethod(
        Invocation.method(
          #removeProfile,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveJanitorId({required int? accessId}) => super.noSuchMethod(
        Invocation.method(
          #saveJanitorId,
          [],
          {#accessId: accessId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getId() => (super.noSuchMethod(
        Invocation.method(
          #getId,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void removeList() => super.noSuchMethod(
        Invocation.method(
          #removeList,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveCheckIn({required bool? isCheckedIn}) => super.noSuchMethod(
        Invocation.method(
          #saveCheckIn,
          [],
          {#isCheckedIn: isCheckedIn},
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isCheckedIn() => (super.noSuchMethod(
        Invocation.method(
          #isCheckedIn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  void removeCheckValue() => super.noSuchMethod(
        Invocation.method(
          #removeCheckValue,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveRoleId({required int? accessRoleId}) => super.noSuchMethod(
        Invocation.method(
          #saveRoleId,
          [],
          {#accessRoleId: accessRoleId},
        ),
        returnValueForMissingStub: null,
      );

  @override
  int getRoleId() => (super.noSuchMethod(
        Invocation.method(
          #getRoleId,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void saveSupervisorName({required String? accessSupervisorName}) =>
      super.noSuchMethod(
        Invocation.method(
          #saveSupervisorName,
          [],
          {#accessSupervisorName: accessSupervisorName},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getSupervisorName() => (super.noSuchMethod(
        Invocation.method(
          #getSupervisorName,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getSupervisorName,
            [],
          ),
        ),
      ) as String);

  @override
  void removeSupervisorName() => super.noSuchMethod(
        Invocation.method(
          #removeSupervisorName,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveMobileNumber({required String? accessMobileNumber}) =>
      super.noSuchMethod(
        Invocation.method(
          #saveMobileNumber,
          [],
          {#accessMobileNumber: accessMobileNumber},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getMobileNumber() => (super.noSuchMethod(
        Invocation.method(
          #getMobileNumber,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getMobileNumber,
            [],
          ),
        ),
      ) as String);

  @override
  void removeMobileNumber() => super.noSuchMethod(
        Invocation.method(
          #removeMobileNumber,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveLocation({required String? accessLocation}) => super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [],
          {#accessLocation: accessLocation},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getLocation() => (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLocation,
            [],
          ),
        ),
      ) as String);

  @override
  void removeLocation() => super.noSuchMethod(
        Invocation.method(
          #removeLocation,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveLattitude({required String? accessLatitude}) => super.noSuchMethod(
        Invocation.method(
          #saveLattitude,
          [],
          {#accessLatitude: accessLatitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getLatitude() => (super.noSuchMethod(
        Invocation.method(
          #getLatitude,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLatitude,
            [],
          ),
        ),
      ) as String);

  @override
  void removeLatitude() => super.noSuchMethod(
        Invocation.method(
          #removeLatitude,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveLongitude({required String? accessLongitude}) => super.noSuchMethod(
        Invocation.method(
          #saveLongitude,
          [],
          {#accessLongitude: accessLongitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getLongitude() => (super.noSuchMethod(
        Invocation.method(
          #getLongitude,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLongitude,
            [],
          ),
        ),
      ) as String);

  @override
  void removeLongitude() => super.noSuchMethod(
        Invocation.method(
          #removeLongitude,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void saveTime({required String? accessTime}) => super.noSuchMethod(
        Invocation.method(
          #saveTime,
          [],
          {#accessTime: accessTime},
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getTime() => (super.noSuchMethod(
        Invocation.method(
          #getTime,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getTime,
            [],
          ),
        ),
      ) as String);

  @override
  void removeTime() => super.noSuchMethod(
        Invocation.method(
          #removeTime,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GetStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStorage extends _i1.Mock implements _i2.GetStorage {
  MockGetStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Microtask get microtask => (super.noSuchMethod(
        Invocation.getter(#microtask),
        returnValue: _FakeMicrotask_0(
          this,
          Invocation.getter(#microtask),
        ),
      ) as _i2.Microtask);

  @override
  _i3.GetQueue get queue => (super.noSuchMethod(
        Invocation.getter(#queue),
        returnValue: _FakeGetQueue_1(
          this,
          Invocation.getter(#queue),
        ),
      ) as _i3.GetQueue);

  @override
  set queue(_i3.GetQueue? _queue) => super.noSuchMethod(
        Invocation.setter(
          #queue,
          _queue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<bool> get initStorage => (super.noSuchMethod(
        Invocation.getter(#initStorage),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  set initStorage(_i7.Future<bool>? _initStorage) => super.noSuchMethod(
        Invocation.setter(
          #initStorage,
          _initStorage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> get changes => (super.noSuchMethod(
        Invocation.getter(#changes),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i2.ValueStorage<Map<String, dynamic>> get listenable => (super.noSuchMethod(
        Invocation.getter(#listenable),
        returnValue: _FakeValueStorage_2<Map<String, dynamic>>(
          this,
          Invocation.getter(#listenable),
        ),
      ) as _i2.ValueStorage<Map<String, dynamic>>);

  @override
  T? read<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #read,
        [key],
      )) as T?);

  @override
  T getKeys<T>() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #getKeys,
            [],
          ),
        ),
      ) as T);

  @override
  T getValues<T>() => (super.noSuchMethod(
        Invocation.method(
          #getValues,
          [],
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #getValues,
            [],
          ),
        ),
      ) as T);

  @override
  bool hasData(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hasData,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.VoidCallback listen(_i8.VoidCallback? value) => (super.noSuchMethod(
        Invocation.method(
          #listen,
          [value],
        ),
        returnValue: () {},
      ) as _i8.VoidCallback);

  @override
  _i8.VoidCallback listenKey(
    String? key,
    _i9.ValueSetter<dynamic>? callback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenKey,
          [
            key,
            callback,
          ],
        ),
        returnValue: () {},
      ) as _i8.VoidCallback);

  @override
  _i7.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void writeInMemory(
    String? key,
    dynamic value,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #writeInMemory,
          [
            key,
            value,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> writeIfNull(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeIfNull,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> erase() => (super.noSuchMethod(
        Invocation.method(
          #erase,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> save() => (super.noSuchMethod(
        Invocation.method(
          #save,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i4.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);

  @override
  _i7.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i10.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i7.Future<_i4.Response>.value(_FakeResponse_3(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i7.Future<_i4.Response>);

  @override
  _i7.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<_i11.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i7.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i7.Future<_i11.Uint8List>);

  @override
  _i7.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i7.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_4(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i7.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
