// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQZlUtH8um0A0sr4GGiFuqF0An-Wq0zWY',
    appId: '1:620752914415:web:21f056822480e82ce4581a',
    messagingSenderId: '620752914415',
    projectId: 'woloo-44ef1',
    authDomain: 'woloo-44ef1.firebaseapp.com',
    databaseURL: 'https://woloo-44ef1.firebaseio.com',
    storageBucket: 'woloo-44ef1.appspot.com',
    measurementId: 'G-Y3E0EZKD0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyJDAP9AhZDNDvFxB82N816xjWG9Lmji0',
    appId: '1:620752914415:android:4679f9390af10d7ce4581a',
    messagingSenderId: '620752914415',
    projectId: 'woloo-44ef1',
    databaseURL: 'https://woloo-44ef1.firebaseio.com',
    storageBucket: 'woloo-44ef1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnqhrBVa89ey6O8b6xGvlx2UOmD6Np6Go',
    appId: '1:620752914415:ios:feb638491e30fb97e4581a',
    messagingSenderId: '620752914415',
    projectId: 'woloo-44ef1',
    databaseURL: 'https://woloo-44ef1.firebaseio.com',
    storageBucket: 'woloo-44ef1.appspot.com',
    androidClientId: '620752914415-4b90lfeprnceaoflhtiustd22l1j65vo.apps.googleusercontent.com',
    iosClientId: '620752914415-ht6aonfdrq6688h459s7rsqmu7ffduh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.janitor',
  );
}
